spring:
  datasource:
    username: admin
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    password: 'admin'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    hibernate:
      ddl-auto: 'update'
    
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit_admin
    password: .123-321.